services:
    following.twig_extension:
        class: AppBundle\Twig\Extension\FollowingExtension
        public: false
        arguments:
            - '@doctrine'
        tags:
            - { name: twig.extension }

    long_time.twig_extension:
        class: AppBundle\Twig\Extension\LongTimeExtension
        public: false
        tags:
            - { name: twig.extension }

    liked.twig_extension:
        class: AppBundle\Twig\Extension\LikedExtension
        public: false
        arguments:
            - '@doctrine'
        tags:
            - { name: twig.extension }

    user_stats.twig_extension:
            class: AppBundle\Twig\Extension\UserStatsExtension
            public: false
            arguments:
                - '@doctrine'
            tags:
                - { name: twig.extension }

    get_user.twig_extension:
                class: AppBundle\Twig\Extension\GetUserExtension
                public: false
                arguments:
                    - '@doctrine'
                tags:
                    - { name: twig.extension }